### ISSUE TITLE
关于CF_Diff

### ISSUE THREAD

**Issue by akajinchen** [Ricardo-Ping/ChaoRec#1]
hi，感谢你开源的框架，我想知道这个框架里的CF_Diff与原作者开源的有什么区别吗

**Comment by Ricardo-Ping** [comment]
是按照源代码复现的，但不能保证没有问题存在

**Comment by akajinchen** [comment]
> 是按照源代码复现的，但不能保证没有问题存在

原文代码里好像没有实现multi-hop的代码

**Comment by Ricardo-Ping** [comment]
是的，只有两跳，只复现了两跳
